### ISSUE TITLE
Organize the notes link 

### ISSUE THREAD

**Issue by iammanishk** [iammanishk/Python-DSA#1]
Organize the links of the notes in the readme main readme file in a readable manner

**Comment by abhi-jeet-kumar** [comment]
Hey @iammanishk I am interested. Can you explain your expected change with an example, please?
I'll raise a PR soon after that

**Comment by iammanishk** [comment]
> Hey @iammanishk I am interested. Can you explain your expected change with an example, please? I'll raise a PR soon after that

Hey Abhijeet first of all Sorry for the late reply. Look there is a link in this readme file that connects all the notes but due to time issues, I have not organized it so you have to do the same. And I've recently opened a new issue if you are interested then go for that also.
